INCLUDES=./includes/
SOURCE=./src/*.c

all: INCLUDES=./includes/
SOURCE=./src/*.c

all:
	 gcc  $(SOURCE) -I $(INCLUDES) -o database

run: ./database

gcc  $(SOURCE) -I $(INCLUDES) -o database
run: ./database

